apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
spec:
  # minReadySeconds: 30
  selector:
    matchLabels:
      app: helloworld
  replicas: 2
  template: # template for the pods
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: hkdemircan/hello-world-image:v1

---
apiVersion: v1
kind: Service
metadata:
  name: hkdemircan-helloworld

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: helloworld

  ports:
    - name: http
      port: 8080
      nodePort: 30080

  type: NodePort
